export const myWork = [
  {},
  {
    title: "First Group Project.",
    src: "./images/screenshotFinal.png",
    alt: "Project 1 From BootCamp",
    deployTitle: "Vac-cin-ation",
    deployed: "https://jonmorg-hs.github.io/Project1/",
    github: "https://github.com/jonmorg-hs/Project1",
    info: "A covid smart travel website. This project was made during lock-down, the idea came about by the desire to leave this city. Even just for a week. It is a travel website that shows current covid information in the destination country. ",
  },
  {
    title: "Second Group Project.",
    src: "./images/PsuedoShopper.png",
    alt: "Project 2 From BootCamp",
    deployTitle: "PsuedoShopper",
    deployed: "https://psuedoshopper.herokuapp.com/",
    github: "https://github.com/Thomas21119/PsuedoShopper",
    info: "A trading website. That trades nothing in particular. But it does demonstrate multiple users interacting, buying and selling. It is a framework to show a website can have its own economy, even if it has no reason. It also charts the sale price of an item every time it sells",
  },
  {
    title: "First Full Stack app",
    src: "./images/techBlogging.png",
    alt: "A Small Tech Blogging Site",
    deployTitle: "Tech Blogger",
    deployed: "https://techin-n-blogin.herokuapp.com/",
    github: "https://github.com/TomIHAU/tech-blog/",
    info: "A Blogging website. It is made for blogging about technology, but users can write about anything. Users can comment on each others posts, and a user has full CRUD functionality on both posts and comments ",
  },
  {
    title: "Weather Forecast Dashboard.",
    src: "./images/weatherdash.png",
    alt: "Five day weather forecast",
    deployTitle: "Weather Forecast",
    deployed: "https://tomihau.github.io/WeatherDashboard/",
    github: "https://github.com/TomIHAU/WeatherDashboard",
    info: "Nunc pharetra finibus est at efficitur. Praesent sed congue diam. Integer gravida dui mauris, ut interdum nunc egestas sed. Aenean sedmollis diam. Nunc aliquet risus ac finibus porta. Nam quis arcu non  lectus tincidunt fermentum. Suspendisse aliquet orci porta quam semper  imperdiet. Praesent euismod mi justo, faucibus scelerisque risus cursus  in. Sed rhoncus molli",
  },
  {
    title: "Time management website.",
    src: "./images/timeblock.png",
    alt: "Time management website",
    deployTitle: "Time Block",
    deployed: "https://tomihau.github.io/timeblock/",
    github: "https://github.com/TomIHAU/timeblock",
    info: "Nunc pharetra finibus est at efficitur. Praesent sed congue diam. Integer gravida dui mauris, ut interdum nunc egestas sed. Aenean sedmollis diam. Nunc aliquet risus ac finibus porta. Nam quis arcu non  lectus tincidunt fermentum. Suspendisse aliquet orci porta quam semper  imperdiet. Praesent euismod mi justo, faucibus scelerisque risus cursus  in. Sed rhoncus molli",
  },
  {
    title: "Basic Quiz website.",
    src: "./images/Quizing.png",
    alt: "Quiz website",
    deployTitle: "QuizSite",
    deployed: "https://tomihau.github.io/QuizWebsite/",
    github: "https://github.com/TomIHAU/QuizWebsite",
    info: "Nunc pharetra finibus est at efficitur. Praesent sed congue diam. Integer gravida dui mauris, ut interdum nunc egestas sed. Aenean sedmollis diam. Nunc aliquet risus ac finibus porta. Nam quis arcu non  lectus tincidunt fermentum. Suspendisse aliquet orci porta quam semper  imperdiet. Praesent euismod mi justo, faucibus scelerisque risus cursus  in. Sed rhoncus molli",
  },
];
