export const myWork = [
  {},
  {
    title: "EasyMeal.",
    src: "./images/easyMeal.png",
    alt: "Easy meal easy life",
    deployTitle: "EasyMeal",
    deployed: "https://easymealeasylife.herokuapp.com/",
    github: "https://github.com/TomIHAU/easyMeal",
    info: "An e-commerce app that allows the user to purchase and plan their weeks meals. A solo MERN project made in two . Uses graphql and SQL, the final project for a web dev boot camp.",
  },
  {
    title: "Covid Travel Information Website.",
    src: "./images/screenshotFinal.png",
    alt: "Project 1 From BootCamp",
    deployTitle: "Vac-cin-ation",
    deployed: "https://jonmorg-hs.github.io/Project1/",
    github: "https://github.com/jonmorg-hs/Project1",
    info: "A covid smart travel website. This project was made during lock-down, the idea came about by the desire to leave this city. Even just for a week. It is a travel website that shows current covid information in the destination country. ",
  },
  {
    title: "Weather Forecast Dashboard.",
    src: "./images/weather.png",
    alt: "Five day weather forecast",
    deployTitle: "Weather Forecast",
    deployed: "https://tomihau.github.io/WeatherDashboard/",
    github: "https://github.com/TomIHAU/WeatherDashboard",
    info: "A website that you can search a city's name, and it returns a five day weather forecast. The last five unique searches are kept in local storage. So the user can get results from a previous city at the click of a button!",
  },
  {
    title: "A trading website, PsuedoShopper.",
    src: "./images/PsuedoShopper.png",
    alt: "Project 2 From BootCamp",
    deployTitle: "PsuedoShopper",
    deployed: "https://psuedoshopper.herokuapp.com/",
    github: "https://github.com/Thomas21119/PsuedoShopper",
    info: "A trading website. That trades nothing in particular. But it does demonstrate multiple users interacting, buying and selling. It is a framework to show a website can have its own economy, even if it has no reason. It also charts the sale price of an item every time it sells",
  },
  {
    title: "Tech Blogger.",
    src: "./images/techBlogging.png",
    alt: "A Small Tech Blogging Site",
    deployTitle: "Tech Blogger",
    deployed: "https://techin-n-blogin.herokuapp.com/",
    github: "https://github.com/TomIHAU/tech-blog/",
    info: "A Blogging website. It is made for blogging about technology, but users can write about anything. Users can comment on each others posts, and a user has full CRUD functionality on both posts and comments ",
  },
  {
    title: "Basic Quiz website.",
    src: "./images/Quizing.png",
    alt: "Quiz website",
    deployTitle: "QuizSite",
    deployed: "https://tomihau.github.io/QuizWebsite/",
    github: "https://github.com/TomIHAU/QuizWebsite",
    info: "Just a little Quiz. Its honest. It only has three questions. The site allows users to save their score on a leaderboard, the top five score are shown. It really appeals to the competitive users. ",
  },
  {
    title: "Time management website.",
    src: "./images/timeblock.png",
    alt: "Time management website",
    deployTitle: "Time Block",
    deployed: "https://tomihau.github.io/timeblock/",
    github: "https://github.com/TomIHAU/timeblock",
    info: "An hourly breakdown of the workday, allows the users to input what tasks they need to do at what time. Also changes the color of the background of the tasks depending on the current time",
  },
];
